### ISSUE TITLE
Please send me the usage of your program

### ISSUE THREAD

**Issue by lianboli** [sa7818/GDD#22]
Including input parameters and output. If output is file, please tell me the path and file name. And give me an example, just like this:
$ nosetests src/testsuite

Thanks

**Comment by fd6713** [comment]
$ nosetests src/testsuite
This command has not input and output. It just runs some test files and print the results.

**Comment by lianboli** [comment]
Thank you.

**Comment by lianboli** [comment]
If you do not comment, you can change makefile by yourself. Thanks

**Comment by salaee** [comment]
main.py and gdd_extended.py are independent files and scripts. It is not necessary to put them into the Makefile, and I even doubt if it's possible to use them in the Makefile because of the way they are written.
About gdd.py:
it gets 3 parameters :  
1) filename of csv ( from ../csv_data/*.csv)   
2) Tbase  is a float number for 'tbase'
3) Tupper is a float number for 'tupper' or threshold that we defined.
within this script, it creates a .gdd file in the same directory as csv file.
so its only output is a*.gdd file that has the gdd calculated value of each day and also the accumulated gdd up to that day of the year.
it does not create or generate any plots.
OUTPUT : filename which is the same as first parameter but with '.gdd' extension.

@lianboli, if you had any questions. don't hesitate.

**Comment by lianboli** [comment]
ok, thank you very much. That is what i need.

**Comment by fd6713** [comment]
For download.py:
input arguments: stationid_year (e.g. 50089_2015)
Output: a filename like stationid_year.csv (e.g. 50089_2015.csv)
For bokeh_html.py
input arguments: a csv file (e.g. 50089_2015.csv)
output: a html file (e.g. 50089_2015_bokeh_min_max.csv)

@lianboli 
One important point: in the make file you're using python3.5 in the command which is not a good practice because someone might not have the python 3.5.
You have to use python as a general command which includes all python versions and also works for the user's default python in his computer.

**Comment by SharonQSY** [comment]
Hi, LIanbo
Could you please help me add plot.py into makefile?
For plot.py, it can plot min and max temp , it can also plot accumulated gdd.
if the input argument is .csv file, it will run plot_maxmin(eg:50089_2015.csv)
output : an image with .png format (eg:50089_2015.png)

 If the input argument is .gdd file, it will run plot_gdd(filename1, filename2, filename3) function, filename would be .gdd file. and the argument can be just one,or two, at most three. eg(plot_gdd(50089_2014.gdd,None,None) or plot_gdd(50089_2014.gdd,50089_2015.gdd,None) o r(plot_gdd(50089_2014.gdd,50089_2015.gdd,None50089_2013.gdd)
output:an image with .png format (eg:plot_gdd_50089_2015.png)

Thanks

**Comment by SharonQSY** [comment]
Hi @lianboli 
I just upload analyze_gdd.py.For analyze_gdd.py

Input arguments:analyze_gdd(filename1, filename2, filename3). filename1,filename2 and filename3 are .csv data file. and the argument can just one, or two and at most three. 
eg:analyze_gdd(filename1, None, None) or analyze_gdd(filename1, filename2, None) or analyze_gdd(filename1, filename2, filename3)
 
output: an image with .png format (eg:analyze_gdd.png)

**Comment by lianboli** [comment]
Makefile has been updated. Please test it.
Remember to give me a command line example for your program.
Thanks
